services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: patient-registry
      MYSQL_USER: patient
      MYSQL_PASSWORD: patientpass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-ppatient" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  patient-registry-rest-api:
    build: .
    container_name: patient-registry-rest-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/patient-registry?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: patient
      SPRING_DATASOURCE_PASSWORD: patientpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: